version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/football-stats-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"