version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
       - "8000:8000"  # Serwer Django
    environment:
      - DJANGO_SETTINGS_MODULE=football_stats_backend.settings
    command: >
      sh -c "
        cd /app/frontend/football-stats-frontend &&
        npm install &&
        npm run build &&
        cd /app/backend/football_stats_backend &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
