version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: football_stats_backend.settings
      PYTHONUNBUFFERED: 1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend/football-stats-frontend:/app/frontend
    ports:
      - "3000:3000"
